name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm (for speed)
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: |
            package.json
            backend/package.json
      - name: Install root tools
        run: npm install
      - name: Install backend deps
        working-directory: backend
        run: npm ci || npm install
      - name: Lint
        run: npm run lint
      - name: Seed DB
        working-directory: backend
        run: node seed.js
      - name: Lint placeholder
        run: echo "ESLint to be added in next phase" && true
      - name: Test
        working-directory: backend
        env:
          JWT_SECRET: ci_secret
        run: npm run test:ci
      - name: Coverage summary
        if: always()
        working-directory: backend
        run: |
          echo "\n== Coverage Summary ==\n"
          test -f coverage/lcov.info && tail -n +1 coverage/lcov.info | sed -n '1,20p' || true

